[workspace]
members = ["cuda", "cublas", "nccl", "search-cuda-tools"]
resolver = "2"

[workspace.dependencies]
bindgen = "0.69"
build-script-cfg = "0.0"
find_cuda_helper = "0.2"
half_ = { version = "2.4", package = "half" }
