[workspace]
members = ["cuda", "cublas", "nccl", "search-cuda-tools", "search-corex-tools"]
resolver = "2"

[workspace.dependencies]
half = "2.4"
bindgen = "0.71"
build-script-cfg = "0.0"
find_cuda_helper = "0.2"
