[package]
name = "cuda"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half.workspace = true
log = "0.4"

[build-dependencies]
bindgen.workspace = true
build-script-cfg.workspace = true
search-cuda-tools = { path = "../search-cuda-tools" }
