[package]
name = "cuda"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1"
half_ = { version = "2.4", package = "half", optional = true }
log = "0.4"

[build-dependencies]
bindgen.workspace = true
search-cuda-tools = { path = "../search-cuda-tools" }

[features]
default = ["half"]
half = ["half_"]
